### ISSUE TITLE
[Question] How can I change the version of fabric kotlin

### ISSUE THREAD

**Issue by SettingDust** [ModdingX/Moonstone#10]
I'm gonna to update the fabric kotlin to 1.10.10. But the update button is disabled. So, I modify the file id to the newer.
It will be resetted to 1.10.8. Neither dependencies or installed.

https://github.com/ModdingX/Moonstone/assets/19922286/5cc20754-3101-416d-bcfe-159277c96cf9

**Comment by MelanX** [comment]
Close the file in IntelliJ, open it in another editor, edit and save, reopen in IntelliJ.

I recommend joining the discord server for better/easier support: http://moddingx.org/discord

**Comment by noeppi-noeppi** [comment]
If it is a dependecy, it could be that Moonstone decided that the optimal version is `1.10.8`. This could for example be due to another mod declaring a depency on that exact version instead of the project as a whole. In that case, if you want to update the version, you can either put it on the installed list (where Moonstone will always look for the latest version) or use a version lock. (The `Lock Version` button).
